# Generated by Django 6.0.5 on 2026-06-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_cart',
        ),
    ]
