# Generated by Django 6.0.5 on 2026-06-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='in_cart',
        ),
    ]
