# Generated by Django 6.0.5 on 2026-06-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartitem_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='identifier',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
