# Generated by Django 6.0.5 on 2026-06-18 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.variation'),
        ),
    ]
